name: Check C# Formatting

on:
  push:
    branches:
    - master
    - develop
    - 'fix/*'
    - 'feature/*'

  pull_request:
    branches:
    - master

jobs:
  format:
    runs-on: ubuntu-latest
    name: Run .NET formatter
    steps:
      - uses: actions/checkout@v2
      - run: dotnet tool install -g dotnet-format
      - run: dotnet format ./ --folder --check
